includes("./config/bsp")

set_defaultplat("cross")

-- add_repositories("ldseraph-repo git@github.com:ldseraph/xmake-repo.git main")
-- add_repositories("local-repo repo")
add_requires("gnu-rm")
-- add_requires("bsp-gd32e10x")

set_installdir("./install")
set_toolchains("@gnu-rm")

target("rtthread")
    set_kind("static")
    add_files("rtthread/*.c")
    add_files("rtthread/*.a")
    after_build(function (target)
        print(target:objectfiles())
    end)

target("lora-xmake")
    set_kind("binary")
    add_rules("bsp")
    add_defines("GD32E103V_EVAL","RT_USING_COMPONENTS_INIT","RT_USING_CONSOLE","BSP_USING_UART0","BSP_USING_UART1")
    add_includedirs("vendor/bsp/drivers")
    add_includedirs("vendor/bsp/Library/CMSIS")
    add_includedirs("vendor/bsp/Library/CMSIS/GD/GD32E10x/Include")
    add_includedirs("vendor/bsp/Library/GD32E10x_standard_peripheral/Include")
    add_files("src/*.c")
    add_files("vendor/bsp/startup/gcc/*.s")
    add_files("vendor/bsp/Library/GD32E10x_standard_peripheral/Source/*.c")
    add_files("vendor/bsp/Library/CMSIS/GD/GD32E10x/Source/system_gd32e10x.c")
    add_files("vendor/bsp/*.c")
    add_deps("rtthread")
